version: '3.8'
services:
  # app:
  #   image: outbox-pattern-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #     - rabbitmq
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=Host=db;Database=outbox_test;Username=postgres;Password=postgres

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: outbox_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI

volumes:
  postgres_data:
